Repository boutproject/hypnotoad, pull requests merged in 2021-01, with the labels that each got.

#60 Developer docs update
  README.md
  doc/developer/developer.md
  hypnotoad/gui/README.md
  hypnotoad/gui/hypnotoad_mainWindow.ui
Labels: documentation

#62 Fix setting GUI options using Preferences dialog
  doc/whats-new.md
  hypnotoad/gui/gui.py
Labels: bugfix

#65 Fix failure when using target_poloidal_spacing_length with y_boundary_guards>0
  doc/whats-new.md
  hypnotoad/core/equilibrium.py
  hypnotoad/test_suite/test_equilibrium.py
Labels: bugfix

#64 Monotonic psi spacing
  doc/whats-new.md
  hypnotoad/core/equilibrium.py
  hypnotoad/core/mesh.py
  hypnotoad/test_suite/test_equilibrium.py
Labels: breaking change, enhancement

#69 Write strings as file attributes
  doc/whats-new.md
  hypnotoad/core/mesh.py
  setup.py
Labels: bugfix

#67 Create a UUID for each grid file
  doc/whats-new.md
  hypnotoad/core/mesh.py
Labels: enhancement

#71 Save geqdsk input to grid file
  doc/whats-new.md
  hypnotoad/cases/tokamak.py
  hypnotoad/core/mesh.py
Labels: enhancement

#73 Make extrapolation guaranteed monotonic in getSqrtPoloidalDistanceFunc()
  doc/whats-new.md
  hypnotoad/core/equilibrium.py
  hypnotoad/test_suite/test_equilibrium.py
Labels: enhancement

#75 Per-target settings for target poloidal spacing
  doc/whats-new.md
  hypnotoad/cases/tokamak.py
  hypnotoad/core/equilibrium.py
  hypnotoad/test_suite/test_equilibrium.py
Labels: enhancement

#76 Check for unsupported options in input files
  doc/whats-new.md
  hypnotoad/gui/gui.py
  hypnotoad/scripts/hypnotoad_geqdsk.py
Labels: enhancement

#79 Option to smooth components of curvature vector
  doc/whats-new.md
  hypnotoad/core/mesh.py
Labels: enhancement

#80 Option to start grid from upper-outer divertor instead of lower-inner
  doc/whats-new.md
  hypnotoad/cases/tokamak.py
Labels: enhancement

#86 Check fine contour when created
  doc/whats-new.md
  hypnotoad/core/equilibrium.py
  hypnotoad/test_suite/test_equilibrium.py
Labels: bugfix
